### PR TITLE
added image of "how notification send in big app" infographic

### PR DESCRIPTION
**Pull request by praveeno**
added a image, which i found interesting, it illustrate how a notification will be send, through a infographic.

### CODE REVIEW

**Comment by codylindley** [comment]
Where do you suggest I add this?

**Comment by praveeno** [comment]
maybe under `How things works` or `Backend WorkFlow`, I just found this infographic useful.

**Comment by codylindley** [comment]
Thanks for addition but could not find a place to make this fit.

**Comment by praveeno** [comment]
okay

**Pull request closed without merging**
