### PR TITLE
Remove emotional statement about strict types

### PR DESCRIPTION
**Pull request by abossard**
Except assembler and brainfuck, all programming languages do have types, so that statement "developers don't need types" is wrong. 
It's true that there are developers that don't want type-safety, syntax-coloring, compile time quality checks and solely work with `ed`, but many others appreciate helpful IDE insights, preflight checks and as few runtime errors as possible. 
I suggest to keep it brief and professional instead of trying to shuffle in your personal and biased opinion.
(And no, I don't work for Microsoft)

### CODE REVIEW

**Comment by codylindley** [comment]
I should add a clarification that I am speaking about bolted on types after language design.

**Comment by abossard** [comment]
Then why not add this really helpful overview to the documentation and mention that it's an emotional topic? I think no one comes to this recap to know more about your (valid) opinion, but to know something about the state of Javascript.
I don't say you're wrong, I just think it's the wrong place to put your opinion in.
Reading through the whole thing, that's the only bullet point, that really stands out and has a different tone and unreferenced statements.

**Comment by codylindley** [comment]
Thank you for the respectful discourse I am going to give your request more thought as I think you have a valid point.

**Comment by abossard** [comment]
Thanks for your consideration! Your work is excellent and I love the recap.

What do you mean with "bolted on"? It seems you're using it with a negative
connotation.

Cheers!

**Comment by abossard** [comment]
Ok, that's a very good explanation. I know what you refer too, as e.g. with
Typescript the available Typings are not always up to par and if they
aren't it's horrible.
Maybe it's clearer with a statement like: "languages with optional type
definitions while still being a superset of Javascript may introduce
unexpected additional complexity".
I would leave it to the developers to deal with that warning and derive a
decision from it.

**Pull request closed without merging**
