### PR TITLE
Added content

### PR DESCRIPTION
**Pull request by cferdinandi**
**Newsletters & Podcasts**
- Daily Developer Tips: https://gomakethings.com (newsletter)
- The Vanilla JS Podcast: https://vanillajspodcast.com (podcast)

**Courses**
- The Vanilla JS Academy: https://vanillajsacademy.com

**JavaScript Resources**
- Vanilla JS Pocket Guides: https://vanillajsguides.com
- Daily Developer Tips: https://gomakethings.com
- The Vanilla JS Toolkit: https://vanillajstoolkit.com
- The Vanilla JS Podcast: https://vanillajspodcast.com

### CODE REVIEW

**Comment by 1Marc** [comment]
I love your work, but this is just too much....maybe try just adding your vanilla js link to a PR for the 2019 handbook rather than all 7 links spread throughout the handbook.

**Comment by cferdinandi** [comment]
@1Marc I appreciate that, but the natural question is... which one? I maintain a lot of projects all with different focuses and purpose and on different domains. Any recommendations on what to include and how?

**Comment by 1Marc** [comment]
I initially ran into your work from Chris Coyier linking to https://gomakethings.com/articles/

**Comment by cferdinandi** [comment]
How about this: this PR was opened almost a year ago. 

Rather than me opening another one on the 2019 guide, if you think my stuff would be a good fit anywhere, feel free to add it wherever you deem appropriate. If not, no hard feelings.

**Pull request closed without merging**
